package codionics.db

class PlayerTypeValRepository extends AbstractGenericTypeValRepository[String] {

  override def tableName: String = "players"

  override def pkColumnName: String = "nickname"

  override def isPKAutoGenerated: Boolean = false
}
