package codionics.db

import codionics.domain._

class PlayerRepository extends AbstractTypeValRepository[String] {

  override def tableName: String = "players"

  override def pkColumnName: String = "nickname"

  override def isPKAutoGenerated: Boolean = false
}
